# This is the main values.yaml file for the challenge chart.
# More information can be found in the chart's README.md file.
#
# generated at: 2026-05-12T21:15:50Z
# compose files: docker-compose.yml
# compose hash (sha1): df4c78fea0d227b66cf86fb9388eb32b77eb0125

# Name of the chart (required), basically the name of the project.
name: challenge
apiVersion: v2

# Version of the chart (required)
version: 0.1.0

# Version of the application (required).
# This should be the main application version.
appVersion: 0.1.0
description: A Helm chart for challenge
