# observability_cleanroom/prometheus/docker-compose.yml
services:
  prometheus:
    image: prom/prometheus:v3.0.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-remote-write-receiver
      - --enable-feature=otlp-write-receiver
      - --web.listen-address=:9090
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

volumes:
  prometheus-data: {}
