apiVersion: v1
data:
  POSTGRES_DB: metrics-stack
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: a727b93961fab2067237c143c750d1b3ead5a2ba
    katenary.v3/version: 3.0.0-rc6
  labels:
    {{- include "challenge.labels" . | nindent 4 }}
    katenary.v3/component: db
  name: '{{ include "challenge.fullname" . }}-db'
