apiVersion: v1
data:
  POSTGRES_DB: metrics-stack
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: df4c78fea0d227b66cf86fb9388eb32b77eb0125
    katenary.v3/version: 3.0.0-rc6
  labels:
    {{- include "challenge.labels" . | nindent 4 }}
    katenary.v3/component: db
  name: '{{ include "challenge.fullname" . }}-db'
