package devref

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stevenallen05/localmesh/internal/manifest"
)

func TestWrite_createsFileWithHeader(t *testing.T) {
	repoRoot := t.TempDir()
	if err := os.MkdirAll(filepath.Join(repoRoot, "localmesh"), 0o755); err != nil {
		t.Fatal(err)
	}
	proj := &manifest.Project{Name: "p", LocalDomain: "lvh.me"}
	if err := Write(repoRoot, t.TempDir(), proj, nil); err != nil {
		t.Fatalf("Write: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(repoRoot, "localmesh", "developer_reference.md"))
	if err != nil {
		t.Fatal(err)
	}
	got := string(data)
	if !strings.HasPrefix(got, "# Developer reference\n") {
		t.Errorf("missing title; got first 80 chars = %q", got[:min(80, len(got))])
	}
	if !strings.Contains(got, "Generated by `localmesh build`") {
		t.Errorf("missing 'generated by' note; got = %q", got)
	}
}
