// Package devref renders localmesh/developer_reference.md from project +
// plugin manifests. The file is regenerated on every `localmesh build`
// and tracked in git (precedent: localmesh/bundled.compose.yaml).
//
// Sidecar schema: each plugin MAY ship a
// developer_reference.md.toml next to its plugin.toml, with a required
// `description` string (≤4 lines) and an optional free-form `extras`
// markdown string. Plugins without the sidecar are silently omitted
// from the Plugins section.
package devref

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/stevenallen05/localmesh/internal/manifest"
)

// ingressPort is the LocalMesh-wide ingress gateway port. Source of
// truth: localmesh/service_catalog/security/bootstrap/10-ingress-mesh-gateway.yaml
// and the security plugin's docker-compose.yaml.gotmpl publish line.
// LocalMesh is opinionated, not configurable — when the gateway port
// moves, update it in all three places.
const ingressPort = 8443

// Write renders <repoRoot>/localmesh/developer_reference.md from the
// loaded manifests. repoRoot is used only to construct the output path.
// catalogRoot is used only to locate each plugin's optional sidecar at
// <catalogRoot>/<plugin.Name>/developer_reference.md.toml.
func Write(repoRoot, catalogRoot string, proj *manifest.Project, plugins []*manifest.Plugin) error {
	body := renderDoc(proj, plugins)
	outPath := filepath.Join(repoRoot, "localmesh", "developer_reference.md")
	if err := os.WriteFile(outPath, []byte(body), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	return nil
}

func renderDoc(proj *manifest.Project, plugins []*manifest.Plugin) string {
	// Stub. Subsequent tasks flesh this out.
	return "# Developer reference\n\n> Generated by `localmesh build` from `project.toml` + each plugin's\n> `plugin.toml` / `developer_reference.md.toml`. Do not edit by hand.\n"
}
