// Package devref renders localmesh/developer_reference.md from project +
// plugin manifests. The file is regenerated on every `localmesh build`
// and tracked in git (precedent: localmesh/bundled.compose.yaml).
//
// Sidecar schema: each plugin MAY ship a
// developer_reference.md.toml next to its plugin.toml, with a required
// `description` string (≤4 lines) and an optional free-form `extras`
// markdown string. Plugins without the sidecar are silently omitted
// from the Plugins section.
package devref

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/stevenallen05/localmesh/internal/manifest"
)

// ingressPort is the LocalMesh-wide ingress gateway port. Source of
// truth: localmesh/service_catalog/security/bootstrap/10-ingress-mesh-gateway.yaml
// and the security plugin's docker-compose.yaml.gotmpl publish line.
// LocalMesh is opinionated, not configurable — when the gateway port
// moves, update it in all three places.
const ingressPort = 8443

// Write renders <repoRoot>/localmesh/developer_reference.md from the
// loaded manifests. repoRoot is used only to construct the output path.
// catalogRoot is used only to locate each plugin's optional sidecar at
// <catalogRoot>/<plugin.Name>/developer_reference.md.toml.
func Write(repoRoot, catalogRoot string, proj *manifest.Project, plugins []*manifest.Plugin) error {
	body, err := renderDoc(catalogRoot, proj, plugins)
	if err != nil {
		return err
	}
	outPath := filepath.Join(repoRoot, "localmesh", "developer_reference.md")
	if err := os.WriteFile(outPath, []byte(body), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	return nil
}

func renderDoc(catalogRoot string, proj *manifest.Project, plugins []*manifest.Plugin) (string, error) {
	var b strings.Builder
	b.WriteString("# Developer reference\n\n")
	b.WriteString("> Generated by `localmesh build` from `project.toml` + each plugin's\n")
	b.WriteString("> `plugin.toml` / `developer_reference.md.toml`. Do not edit by hand.\n\n")
	writeProjectBlock(&b, proj)
	writeIngressBlock(&b, proj, plugins)
	if err := writePluginsBlock(&b, catalogRoot, plugins); err != nil {
		return "", err
	}
	return b.String(), nil
}

type ingressRow struct{ url, container, source string }

func writeIngressBlock(b *strings.Builder, proj *manifest.Project, plugins []*manifest.Plugin) {
	rows := ingressRows(proj, plugins)
	b.WriteString("## Ingress\n\n")
	b.WriteString("| URL | Container | Source |\n")
	b.WriteString("|-----|-----------|--------|\n")
	for _, r := range rows {
		fmt.Fprintf(b, "| %s | %s | %s |\n", r.url, r.container, r.source)
	}
	b.WriteString("\n")
}

func ingressRows(proj *manifest.Project, plugins []*manifest.Plugin) []ingressRow {
	out := []ingressRow{}
	for _, s := range proj.Services {
		if s.ExposeViaIngress {
			out = append(out, ingressRow{
				url:       ingressURL(s.Container, proj.Name, proj.LocalDomain),
				container: s.Container,
				source:    "project",
			})
		}
	}
	for _, p := range plugins {
		for _, s := range p.Services {
			if s.ExposeViaIngress {
				out = append(out, ingressRow{
					url:       ingressURL(s.Container, proj.Name, proj.LocalDomain),
					container: s.Container,
					source:    p.Name,
				})
			}
		}
	}
	return out
}

func ingressURL(container, projectName, localDomain string) string {
	return fmt.Sprintf("https://%s.%s.%s:%d", container, projectName, localDomain, ingressPort)
}

func writeProjectBlock(b *strings.Builder, proj *manifest.Project) {
	rows := projectRows(proj)
	b.WriteString("## Project\n\n")
	b.WriteString("| Field             | Value                          |\n")
	b.WriteString("|-------------------|--------------------------------|\n")
	for _, r := range rows {
		fmt.Fprintf(b, "| %-17s | %-30s |\n", r.field, r.value)
	}
	b.WriteString("\n_To change any of these, edit `project.toml` and re-run `localmesh build`._\n\n")
}

type projectRow struct{ field, value string }

func projectRows(proj *manifest.Project) []projectRow {
	// Spec field order: name → namespace → tech lead → external_domain → local_domain.
	// Empty values drop the entire row (mirrors envwriter.buildManaged).
	candidates := []projectRow{
		{"project_name", proj.Name},
		{"project_namespace", proj.Namespace},
		{"tech_lead_email", proj.TechLead},
		{"external_domain", proj.ExternalDomain},
		{"local_domain", proj.LocalDomain},
	}
	out := make([]projectRow, 0, len(candidates))
	for _, r := range candidates {
		if r.value != "" {
			out = append(out, r)
		}
	}
	return out
}

// sidecar mirrors developer_reference.md.toml.
type sidecar struct {
	Description string `toml:"description"`
	Extras      string `toml:"extras"`
}

func writePluginsBlock(b *strings.Builder, catalogRoot string, plugins []*manifest.Plugin) error {
	b.WriteString("## Plugins\n\n")
	for _, p := range plugins {
		sc, present, err := readSidecar(catalogRoot, p.Name)
		if err != nil {
			return err
		}
		if !present {
			continue
		}
		fmt.Fprintf(b, "### %s\n", p.Name)
		b.WriteString(strings.TrimRight(sc.Description, "\n"))
		b.WriteString("\n")
		if sc.Extras != "" {
			b.WriteString("\n")
			b.WriteString(strings.TrimRight(sc.Extras, "\n"))
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}
	return nil
}

// readSidecar returns (parsed, present, error). Missing file → (_, false, nil).
func readSidecar(catalogRoot, pluginName string) (sidecar, bool, error) {
	path := filepath.Join(catalogRoot, pluginName, "developer_reference.md.toml")
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return sidecar{}, false, nil
		}
		return sidecar{}, false, fmt.Errorf("read %s: %w", path, err)
	}
	var sc sidecar
	if err := toml.Unmarshal(data, &sc); err != nil {
		return sidecar{}, false, fmt.Errorf("parse %s: %w", path, err)
	}
	return sc, true, nil
}
