# observability_cleanroom/pyroscope/docker-compose.yml
services:
  pyroscope:
    image: grafana/pyroscope:1.10.0
    container_name: pyroscope
    command: ["-config.file=/etc/pyroscope/pyroscope.yaml"]
    ports:
      - "4040:4040"
    volumes:
      - ./pyroscope.yaml:/etc/pyroscope/pyroscope.yaml:ro
      - pyroscope-data:/data
    restart: unless-stopped

volumes:
  pyroscope-data: {}
