apiVersion: v1
data:
  GRAFANA_API_TOKEN_FILE: /run/grafana/token
  GRAFANA_API_URL: http://grafana:3000
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  OTEL_SERVICE_NAME: server
  SERVER_ADDR: 0.0.0.0:50051
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: 9614b8d906d3bb452a7f021f748707c4574fa522
    katenary.v3/version: 3.0.0-rc6
  labels:
    {{- include "challenge.labels" . | nindent 4 }}
    katenary.v3/component: server
  name: '{{ include "challenge.fullname" . }}-server'
