apiVersion: v1
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  OTEL_SERVICE_NAME: server
  SERVER_ADDR: 0.0.0.0:50051
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: 7254d38a3901f929396e016f1e161398870c9378
    katenary.v3/version: 3.0.0-rc6
  labels:
    {{- include "challenge.labels" . | nindent 4 }}
    katenary.v3/component: server
  name: '{{ include "challenge.fullname" . }}-server'
