{{- if .Values.server.persistence.grafana_token.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    katenary.v3/compose-hash: 9614b8d906d3bb452a7f021f748707c4574fa522
    katenary.v3/version: 3.0.0-rc6
  labels:
    {{- include "challenge.labels" . | nindent 4 }}
    katenary.v3/component: server
  name: '{{ include "challenge.fullname" . }}-server-grafana-token'
spec:
  accessModes:
  {{- .Values.server.persistence.grafana_token.accessMode | toYaml | nindent 2 }}
  resources:
    requests:
      storage: {{ tpl .Values.server.persistence.grafana_token.size $ }}
  {{- if ne .Values.server.persistence.grafana_token.storageClass "-" }}
  storageClassName: '{{ .Values.server.persistence.grafana_token.storageClass }}'
  {{- end }}

{{- end }}