apiVersion: v1
kind: Service
metadata:
  annotations:
    katenary.v3/compose-hash: df4c78fea0d227b66cf86fb9388eb32b77eb0125
    katenary.v3/version: 3.0.0-rc6
  labels:
    {{- include "challenge.labels" . | nindent 4 }}
    katenary.v3/component: server
  name: '{{ include "challenge.fullname" . }}-server'
spec:
  ports:
  - name: port-50051
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    {{- include "challenge.selectorLabels" . | nindent 4 }}
    katenary.v3/component: server
