apiVersion: v1
data:
  SERVER_ADDR: '{{ .Release.Name }}-server:50051'
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: 7733532c3b9d2a756b726783597823af12b5c2c2
    katenary.v3/version: 3.0.0-rc6
  labels:
    {{- include "challenge.labels" . | nindent 4 }}
    katenary.v3/component: www
  name: '{{ include "challenge.fullname" . }}-www'
