apiVersion: v1
data:
  SERVER_ADDR: server:50051
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: 4699ea1910dd933452c90a151d9ab423a1723f4f
    katenary.v3/version: 3.0.0-rc6
  labels:
    {{- include "challenge.labels" . | nindent 4 }}
    katenary.v3/component: www
  name: '{{ include "challenge.fullname" . }}-www'
