apiVersion: v1
data:
  HOSTNAME: agentbox-challenge
  NEXT_PUBLIC_GRAFANA_URL: http://localhost:3001
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
  OTEL_SERVICE_NAME: www
  SERVER_ADDR: '{{ .Release.Name }}-server:50051'
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: 9614b8d906d3bb452a7f021f748707c4574fa522
    katenary.v3/version: 3.0.0-rc6
  labels:
    {{- include "challenge.labels" . | nindent 4 }}
    katenary.v3/component: www
  name: '{{ include "challenge.fullname" . }}-www'
