apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    katenary.v3/compose-hash: 9614b8d906d3bb452a7f021f748707c4574fa522
    katenary.v3/version: 3.0.0-rc6
  labels:
    {{- include "challenge.labels" . | nindent 4 }}
    katenary.v3/component: www
  name: '{{ include "challenge.fullname" . }}-www'
spec:
  replicas: {{ .Values.www.replicas }}
  selector:
    matchLabels:
      {{- include "challenge.selectorLabels" . | nindent 6 }}
      katenary.v3/component: www
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "challenge.selectorLabels" . | nindent 8 }}
        katenary.v3/component: www
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: '{{ include "challenge.fullname" . }}-www'
        image: '{{ tpl .Values.www.repository.image $ }}:{{ tpl .Values.www.repository.tag $ | default "latest" }}'
        imagePullPolicy: {{ .Values.www.imagePullPolicy }}
        livenessProbe:
          exec:
            command:
            - wget
            - -qO-
            - http://localhost:3000/
          periodSeconds: 10
        name: www
        ports:
        - containerPort: 3000
          name: port-3000
        {{- if .Values.www.resources }}
        resources:
          {{ .Values.www.resources | toYaml | nindent 10 }}
        {{- end }}
      {{- if .Values.pullSecrets }}
      imagePullSecrets:
      {{- .Values.pullSecrets | toYaml | nindent 6 }}
      {{- end }}
      initContainers:
      - command:
        - /bin/sh
        - -c
        - |-
          until nc -z {{ include "challenge.fullname" . }}-server 50051; do
            sleep 1;
          done
        image: busybox:latest
        name: wait-for-server
        {{- if .Values.www.resources }}
        resources:
          {{ .Values.www.resources | toYaml | nindent 10 }}
        {{- end }}
      {{- if .Values.www.nodeSelector }}
      nodeSelector:
        {{- .Values.www.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if ne .Values.www.serviceAccount "" }}
      serviceAccountName: {{ .Values.www.serviceAccount | quote }}
      {{- end }}
