apiVersion: v1
data:
  AGENT_ID: ""
  AGENT_LOG_FORMAT: text
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: c749dab78c1accc49408e4f6844f62f2eeb2ccc4
    katenary.v3/version: 3.0.0-rc6
  labels:
    {{- include "challenge.labels" . | nindent 4 }}
    katenary.v3/component: agent
  name: '{{ include "challenge.fullname" . }}-agent'
