apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    katenary.v3/compose-hash: 7733532c3b9d2a756b726783597823af12b5c2c2
    katenary.v3/version: 3.0.0-rc6
  labels:
    {{- include "challenge.labels" . | nindent 4 }}
    katenary.v3/component: agent
  name: '{{ include "challenge.fullname" . }}-agent'
spec:
  replicas: {{ .Values.agent.replicas }}
  selector:
    matchLabels:
      {{- include "challenge.selectorLabels" . | nindent 6 }}
      katenary.v3/component: agent
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "challenge.selectorLabels" . | nindent 8 }}
        katenary.v3/component: agent
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: '{{ include "challenge.fullname" . }}-agent'
        image: '{{ tpl .Values.agent.repository.image $ }}:{{ tpl .Values.agent.repository.tag $ | default "latest" }}'
        imagePullPolicy: {{ .Values.agent.imagePullPolicy }}
        name: agent
        {{- if .Values.agent.resources }}
        resources:
          {{ .Values.agent.resources | toYaml | nindent 10 }}
        {{- end }}
      {{- if .Values.pullSecrets }}
      imagePullSecrets:
      {{- .Values.pullSecrets | toYaml | nindent 6 }}
      {{- end }}
      {{- if .Values.agent.nodeSelector }}
      nodeSelector:
        {{- .Values.agent.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if ne .Values.agent.serviceAccount "" }}
      serviceAccountName: {{ .Values.agent.serviceAccount | quote }}
      {{- end }}
