{{- if .Values.tempo.persistence.tempo_data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    katenary.v3/compose-hash: 7254d38a3901f929396e016f1e161398870c9378
    katenary.v3/version: 3.0.0-rc6
  labels:
    {{- include "challenge.labels" . | nindent 4 }}
    katenary.v3/component: tempo
  name: '{{ include "challenge.fullname" . }}-tempo-tempo-data'
spec:
  accessModes:
  {{- .Values.tempo.persistence.tempo_data.accessMode | toYaml | nindent 2 }}
  resources:
    requests:
      storage: {{ tpl .Values.tempo.persistence.tempo_data.size $ }}
  {{- if ne .Values.tempo.persistence.tempo_data.storageClass "-" }}
  storageClassName: '{{ .Values.tempo.persistence.tempo_data.storageClass }}'
  {{- end }}

{{- end }}