// Package render merges rendered plugin compose files into a single
// .localmesh/localmesh.compose.yaml per spec §2.5.
package render

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/stevenallen05/localmesh/internal/manifest"
	tmpl "github.com/stevenallen05/localmesh/internal/template"
)

// Run renders every plugin in catalogRoot and writes the merged output
// to outputPath. projectFile is the path to project.toml. Returns an
// error with context on the first failure.
func Run(projectFile, catalogRoot, outputPath string) error {
	proj, plugins, err := manifest.LoadAll(projectFile, catalogRoot)
	if err != nil {
		return err
	}
	return RunWith(proj, plugins, catalogRoot, outputPath)
}

// RunWith is Run with already-loaded manifests. Lets callers (the build
// verb) load once and pass the same structs to both render + envwriter.
//
// Two-pass: pass 1 renders every plugin with an empty Workloads list so
// the merged compose surfaces every container name + its mesh.exempt
// label. The mesh plugin's compose uses .Workloads, so on pass 1 it
// emits only the role services (ingress-mesh, egress-mesh) and no
// sidecar blocks. Pass 2 re-renders any plugin whose template depends
// on .Workloads with the populated list. Today only the mesh plugin
// qualifies, so the second pass re-renders just that one and swaps it
// into the rendered slice before the final merge.
func RunWith(proj *manifest.Project, plugins []*manifest.Plugin, catalogRoot, outputPath string) error {
	env := envMap()
	outputDir := filepath.Dir(outputPath)
	rendered := make([]*yaml.Node, 0, len(plugins))
	sources := make([]string, 0, len(plugins))
	meshIdx := -1
	for i, p := range plugins {
		node, err := renderPluginCompose(proj, p, env, nil, catalogRoot, outputDir)
		if err != nil {
			return err
		}
		rendered = append(rendered, node)
		sources = append(sources, p.Name)
		if p.Name == "mesh" {
			meshIdx = i
		}
	}
	// Discover workloads from pass-1 rendered nodes + project-tier services
	// (proj.Services declares app containers like www, server that live in
	// the root docker-compose.yml, not in any plugin compose). Mesh's
	// pass-1 output is filtered out — its ingress-mesh + egress-mesh are
	// roles, not workloads, and the mesh template never iterates itself.
	//
	// Filter the result to registry-known containers: only services with a
	// declared [[services]] entry have port/scheme metadata, which the
	// sidecar bootstrap needs. Compose-only services (e.g. helper
	// containers like database-collector with no plugin.toml entry) are
	// dropped here so we don't emit a sidecar compose block without a
	// matching envoy YAML.
	if meshIdx >= 0 {
		workloads := workloadsFromNodes(rendered, sources)
		workloads = appendProjectWorkloads(workloads, proj)
		workloads = filterRegistryKnown(workloads, proj, plugins)
		node, err := renderPluginCompose(proj, plugins[meshIdx], env, workloads, catalogRoot, outputDir)
		if err != nil {
			return err
		}
		rendered[meshIdx] = node
	}
	merged, err := Merge(rendered, sources)
	if err != nil {
		return err
	}
	if err := SortServices(merged); err != nil {
		return err
	}
	out, err := yaml.Marshal(merged)
	if err != nil {
		return fmt.Errorf("marshal merged: %w", err)
	}
	header := "# Auto-generated by ./localmesh_src/cmd/localmesh build — do not edit by hand.\n"
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(outputPath), err)
	}
	return os.WriteFile(outputPath, append([]byte(header), out...), 0o644)
}

// renderPluginCompose renders one plugin's docker-compose template + parses
// the output + rewrites relative paths. Factored out so RunWith can call it
// twice (the second pass repopulates .Workloads for the mesh plugin).
func renderPluginCompose(proj *manifest.Project, p *manifest.Plugin, env map[string]string, workloads []tmpl.WorkloadCtx, catalogRoot, outputDir string) (*yaml.Node, error) {
	composePath := pluginComposePath(catalogRoot, p.Name)
	ctx := &tmpl.Context{Project: proj, Plugin: p, Env: env, Workloads: workloads}
	body, err := tmpl.Render(composePath, ctx)
	if err != nil {
		return nil, err
	}
	var node yaml.Node
	if err := yaml.Unmarshal(body, &node); err != nil {
		return nil, fmt.Errorf("parse rendered %s: %w", composePath, err)
	}
	// Relative paths inside each plugin's compose are authored relative
	// to that plugin's dir; rewrite them so they resolve from the merged
	// output's dir instead. Both sides absolutized so filepath.Rel works
	// even when callers pass relative paths.
	absOut, err := filepath.Abs(outputDir)
	if err != nil {
		return nil, fmt.Errorf("abs %s: %w", outputDir, err)
	}
	absPlugin, err := filepath.Abs(filepath.Dir(composePath))
	if err != nil {
		return nil, fmt.Errorf("abs %s: %w", composePath, err)
	}
	relPrefix, err := filepath.Rel(absOut, absPlugin)
	if err != nil {
		return nil, fmt.Errorf("rel path %s -> %s: %w", absOut, absPlugin, err)
	}
	RewriteRelativePaths(&node, relPrefix)
	return &node, nil
}

// filterRegistryKnown drops workloads whose container name doesn't appear
// in any plugin.toml or project.toml [[services]] block. Those entries
// have no port/scheme metadata, so the mesh sidecar render can't generate
// a YAML for them — emitting a compose block for them would point at a
// missing config file.
func filterRegistryKnown(workloads []tmpl.WorkloadCtx, proj *manifest.Project, plugins []*manifest.Plugin) []tmpl.WorkloadCtx {
	known := map[string]bool{}
	for _, s := range proj.Services {
		known[s.Container] = true
	}
	for _, p := range plugins {
		for _, s := range p.Services {
			known[s.Container] = true
		}
	}
	out := make([]tmpl.WorkloadCtx, 0, len(workloads))
	for _, w := range workloads {
		if known[w.Name] {
			out = append(out, w)
		}
	}
	return out
}

// appendProjectWorkloads merges project-tier services (proj.Services) into
// the workload list. These app-tier containers (www, server) live in the
// root docker-compose.yml — not in any plugin compose — so the node walk
// above misses them. They are never mesh-exempt today; if a future need
// arises, mesh-exempt could be expressed in project.toml [[services]].
// Idempotent: existing entries (e.g. when a project service is also
// declared via a plugin block) are preserved.
func appendProjectWorkloads(existing []tmpl.WorkloadCtx, proj *manifest.Project) []tmpl.WorkloadCtx {
	seen := map[string]bool{}
	for _, w := range existing {
		seen[w.Name] = true
	}
	for _, s := range proj.Services {
		if seen[s.Container] {
			continue
		}
		existing = append(existing, tmpl.WorkloadCtx{Name: s.Container, MeshExempt: false})
		seen[s.Container] = true
	}
	sort.Slice(existing, func(i, j int) bool { return existing[i].Name < existing[j].Name })
	return existing
}

// workloadsFromNodes extracts every services.<name> + its mesh.exempt
// label from the pass-1 rendered plugin compose nodes. The mesh plugin's
// own pass-1 output (ingress-mesh, egress-mesh) is excluded — those are
// roles, not workloads, and the mesh template never iterates itself.
// Services appearing in multiple plugins (additive blocks like caddy
// dropping a config onto observability's grafana) are deduped: a service
// is mesh-exempt if any contributing plugin marks it exempt. Result is
// sorted by name for deterministic output.
func workloadsFromNodes(nodes []*yaml.Node, sources []string) []tmpl.WorkloadCtx {
	byName := map[string]tmpl.WorkloadCtx{}
	for i, n := range nodes {
		if sources[i] == "mesh" {
			continue
		}
		if n.Kind != yaml.DocumentNode || len(n.Content) == 0 {
			continue
		}
		top := n.Content[0]
		if top.Kind != yaml.MappingNode {
			continue
		}
		for j := 0; j < len(top.Content); j += 2 {
			k := top.Content[j]
			v := top.Content[j+1]
			if k.Value != "services" || v.Kind != yaml.MappingNode {
				continue
			}
			for s := 0; s < len(v.Content); s += 2 {
				svcName := v.Content[s].Value
				svcBody := v.Content[s+1]
				cur, ok := byName[svcName]
				exempt := serviceLabelEquals(svcBody, "mesh.exempt", "true")
				if !ok {
					byName[svcName] = tmpl.WorkloadCtx{Name: svcName, MeshExempt: exempt}
					continue
				}
				cur.MeshExempt = cur.MeshExempt || exempt
				byName[svcName] = cur
			}
		}
	}
	out := make([]tmpl.WorkloadCtx, 0, len(byName))
	for _, w := range byName {
		out = append(out, w)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// serviceLabelEquals reports whether the given service mapping carries a
// labels entry with key=value. Handles both compose label forms (mapping
// "labels: { key: value }" and sequence "labels: [ key=value ]").
func serviceLabelEquals(svc *yaml.Node, key, value string) bool {
	if svc.Kind != yaml.MappingNode {
		return false
	}
	for i := 0; i < len(svc.Content); i += 2 {
		if svc.Content[i].Value != "labels" {
			continue
		}
		labels := svc.Content[i+1]
		switch labels.Kind {
		case yaml.MappingNode:
			for j := 0; j < len(labels.Content); j += 2 {
				if labels.Content[j].Value == key && labels.Content[j+1].Value == value {
					return true
				}
			}
		case yaml.SequenceNode:
			needle := key + "=" + value
			for _, e := range labels.Content {
				if e.Value == needle {
					return true
				}
			}
		}
	}
	return false
}

func pluginComposePath(catalogRoot, name string) string {
	candidates := []string{
		filepath.Join(catalogRoot, name, "docker-compose.yaml.gotmpl"),
		filepath.Join(catalogRoot, name, "docker-compose.yml.gotmpl"),
		filepath.Join(catalogRoot, name, "docker-compose.yaml"),
		filepath.Join(catalogRoot, name, "docker-compose.yml"),
	}
	for _, p := range candidates {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	// Return the last candidate — the read will fail with a clear error.
	return candidates[len(candidates)-1]
}

func envMap() map[string]string {
	env := os.Environ()
	out := make(map[string]string, len(env))
	for _, e := range env {
		if k, v, ok := strings.Cut(e, "="); ok {
			out[k] = v
		}
	}
	return out
}

// SortServices reorders services.<X> keys alphabetically (spec §2.5).
func SortServices(root *yaml.Node) error {
	if root.Kind != yaml.DocumentNode || len(root.Content) == 0 {
		return nil
	}
	top := root.Content[0]
	if top.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i < len(top.Content); i += 2 {
		k := top.Content[i]
		v := top.Content[i+1]
		if k.Value == "services" && v.Kind == yaml.MappingNode {
			sortMappingKeys(v)
		}
	}
	return nil
}

func sortMappingKeys(m *yaml.Node) {
	type kv struct{ k, v *yaml.Node }
	pairs := make([]kv, 0, len(m.Content)/2)
	for i := 0; i < len(m.Content); i += 2 {
		pairs = append(pairs, kv{m.Content[i], m.Content[i+1]})
	}
	sort.Slice(pairs, func(i, j int) bool { return pairs[i].k.Value < pairs[j].k.Value })
	m.Content = m.Content[:0]
	for _, p := range pairs {
		m.Content = append(m.Content, p.k, p.v)
	}
}
