// Package render merges rendered plugin compose files into a single
// .localmesh/localmesh.compose.yaml per spec §2.5.
package render

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/tensorwave/localmesh/internal/manifest"
	tmpl "github.com/tensorwave/localmesh/internal/template"
)

// Run renders every plugin in catalogRoot and writes the merged output
// to outputPath. projectFile is the path to project.toml. Returns an
// error with context on the first failure.
func Run(projectFile, catalogRoot, outputPath string) error {
	proj, plugins, err := manifest.LoadAll(projectFile, catalogRoot)
	if err != nil {
		return err
	}
	return RunWith(proj, plugins, catalogRoot, outputPath)
}

// RunWith is Run with already-loaded manifests. Lets callers (the build
// verb) load once and pass the same structs to both render + envwriter.
func RunWith(proj *manifest.Project, plugins []*manifest.Plugin, catalogRoot, outputPath string) error {
	env := envMap()
	outputDir := filepath.Dir(outputPath)
	rendered := make([]*yaml.Node, 0, len(plugins))
	sources := make([]string, 0, len(plugins))
	for _, p := range plugins {
		composePath := pluginComposePath(catalogRoot, p.Name)
		ctx := &tmpl.Context{Project: proj, Plugin: p, Env: env}
		body, err := tmpl.Render(composePath, ctx)
		if err != nil {
			return err
		}
		var node yaml.Node
		if err := yaml.Unmarshal(body, &node); err != nil {
			return fmt.Errorf("parse rendered %s: %w", composePath, err)
		}
		// Relative paths inside each plugin's compose are authored relative
		// to that plugin's dir; rewrite them so they resolve from the merged
		// output's dir instead. Both sides absolutized so filepath.Rel works
		// even when callers pass relative paths.
		absOut, err := filepath.Abs(outputDir)
		if err != nil {
			return fmt.Errorf("abs %s: %w", outputDir, err)
		}
		absPlugin, err := filepath.Abs(filepath.Dir(composePath))
		if err != nil {
			return fmt.Errorf("abs %s: %w", composePath, err)
		}
		relPrefix, err := filepath.Rel(absOut, absPlugin)
		if err != nil {
			return fmt.Errorf("rel path %s -> %s: %w", absOut, absPlugin, err)
		}
		RewriteRelativePaths(&node, relPrefix)
		rendered = append(rendered, &node)
		sources = append(sources, p.Name)
	}
	merged, err := Merge(rendered, sources)
	if err != nil {
		return err
	}
	if err := SortServices(merged); err != nil {
		return err
	}
	out, err := yaml.Marshal(merged)
	if err != nil {
		return fmt.Errorf("marshal merged: %w", err)
	}
	header := "# Auto-generated by ./localmesh_src/cmd/localmesh build — do not edit by hand.\n"
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(outputPath), err)
	}
	return os.WriteFile(outputPath, append([]byte(header), out...), 0o644)
}

func pluginComposePath(catalogRoot, name string) string {
	candidates := []string{
		filepath.Join(catalogRoot, name, "docker-compose.yaml.gotmpl"),
		filepath.Join(catalogRoot, name, "docker-compose.yml.gotmpl"),
		filepath.Join(catalogRoot, name, "docker-compose.yaml"),
		filepath.Join(catalogRoot, name, "docker-compose.yml"),
	}
	for _, p := range candidates {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	// Return the last candidate — the read will fail with a clear error.
	return candidates[len(candidates)-1]
}

func envMap() map[string]string {
	env := os.Environ()
	out := make(map[string]string, len(env))
	for _, e := range env {
		if k, v, ok := strings.Cut(e, "="); ok {
			out[k] = v
		}
	}
	return out
}

// SortServices reorders services.<X> keys alphabetically (spec §2.5).
func SortServices(root *yaml.Node) error {
	if root.Kind != yaml.DocumentNode || len(root.Content) == 0 {
		return nil
	}
	top := root.Content[0]
	if top.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i < len(top.Content); i += 2 {
		k := top.Content[i]
		v := top.Content[i+1]
		if k.Value == "services" && v.Kind == yaml.MappingNode {
			sortMappingKeys(v)
		}
	}
	return nil
}

func sortMappingKeys(m *yaml.Node) {
	type kv struct{ k, v *yaml.Node }
	pairs := make([]kv, 0, len(m.Content)/2)
	for i := 0; i < len(m.Content); i += 2 {
		pairs = append(pairs, kv{m.Content[i], m.Content[i+1]})
	}
	sort.Slice(pairs, func(i, j int) bool { return pairs[i].k.Value < pairs[j].k.Value })
	m.Content = m.Content[:0]
	for _, p := range pairs {
		m.Content = append(m.Content, p.k, p.v)
	}
}
