// Package render merges rendered plugin compose files into a single
// .localmesh/localmesh.compose.yaml per spec §2.5.
package render

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/tensorwave/localmesh/internal/manifest"
	tmpl "github.com/tensorwave/localmesh/internal/template"
)

// Run renders every plugin in catalogRoot and writes the merged output
// to outputPath. Returns an error with context on the first failure.
func Run(catalogRoot, outputPath string) error {
	proj, plugins, err := manifest.LoadAll(catalogRoot)
	if err != nil {
		return err
	}
	env := envMap()
	rendered := make([]*yaml.Node, 0, len(plugins))
	sources := make([]string, 0, len(plugins))
	for _, p := range plugins {
		composePath := pluginComposePath(catalogRoot, p.Name)
		ctx := &tmpl.Context{Project: proj, Plugin: p, Env: env}
		body, err := tmpl.Render(composePath, ctx)
		if err != nil {
			return err
		}
		var node yaml.Node
		if err := yaml.Unmarshal(body, &node); err != nil {
			return fmt.Errorf("parse rendered %s: %w", composePath, err)
		}
		rendered = append(rendered, &node)
		sources = append(sources, p.Name)
	}
	merged, err := Merge(rendered, sources)
	if err != nil {
		return err
	}
	if err := SortServices(merged); err != nil {
		return err
	}
	out, err := yaml.Marshal(merged)
	if err != nil {
		return fmt.Errorf("marshal merged: %w", err)
	}
	header := "# Auto-generated by ./localmesh_src/cmd/localmesh build — do not edit by hand.\n"
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(outputPath), err)
	}
	return os.WriteFile(outputPath, append([]byte(header), out...), 0o644)
}

func pluginComposePath(catalogRoot, name string) string {
	tmplPath := filepath.Join(catalogRoot, name, "docker-compose.yaml.gotmpl")
	if _, err := os.Stat(tmplPath); err == nil {
		return tmplPath
	}
	return filepath.Join(catalogRoot, name, "docker-compose.yaml")
}

func envMap() map[string]string {
	env := os.Environ()
	out := make(map[string]string, len(env))
	for _, e := range env {
		if k, v, ok := strings.Cut(e, "="); ok {
			out[k] = v
		}
	}
	return out
}

// SortServices reorders services.<X> keys alphabetically (spec §2.5).
func SortServices(root *yaml.Node) error {
	if root.Kind != yaml.DocumentNode || len(root.Content) == 0 {
		return nil
	}
	top := root.Content[0]
	if top.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i < len(top.Content); i += 2 {
		k := top.Content[i]
		v := top.Content[i+1]
		if k.Value == "services" && v.Kind == yaml.MappingNode {
			sortMappingKeys(v)
		}
	}
	return nil
}

func sortMappingKeys(m *yaml.Node) {
	type kv struct{ k, v *yaml.Node }
	pairs := make([]kv, 0, len(m.Content)/2)
	for i := 0; i < len(m.Content); i += 2 {
		pairs = append(pairs, kv{m.Content[i], m.Content[i+1]})
	}
	sort.Slice(pairs, func(i, j int) bool { return pairs[i].k.Value < pairs[j].k.Value })
	m.Content = m.Content[:0]
	for _, p := range pairs {
		m.Content = append(m.Content, p.k, p.v)
	}
}
