use std::net::SocketAddr;
use tonic::{transport::Server, Request, Response, Status};

// Generated by build.rs into src/proto/. Committed so reviewers see the wire
// shape without running cargo first; see DESIGN_DECISIONS.md.
pub mod hello {
    include!("proto/hello.rs");
}

use hello::greeter_server::{Greeter, GreeterServer};
use hello::{HelloReply, HelloRequest};

#[derive(Default)]
struct GreeterSvc;

#[tonic::async_trait]
impl Greeter for GreeterSvc {
    async fn say_hello(
        &self,
        req: Request<HelloRequest>,
    ) -> Result<Response<HelloReply>, Status> {
        let name = req.into_inner().name;
        let name = if name.is_empty() { "world" } else { &name };
        Ok(Response::new(HelloReply {
            message: format!("hello, {name}"),
        }))
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // TODO: route through a proper config loader (parity with the agent's
    // Koanf setup) once a second config knob shows up. One env var doesn't
    // earn the loader yet.
    let addr: SocketAddr = std::env::var("SERVER_ADDR")
        .unwrap_or_else(|_| "0.0.0.0:50051".to_string())
        .parse()?;
    println!("server: listening on {addr}");
    Server::builder()
        .add_service(GreeterServer::new(GreeterSvc))
        .serve(addr)
        .await?;
    Ok(())
}
