use std::net::SocketAddr;
use std::time::Instant;
use opentelemetry::global;
use opentelemetry::metrics::{Counter, Histogram};
use tonic::{transport::Server, Request, Response, Status};
use tracing::{instrument, Span};
use tracing_opentelemetry::OpenTelemetrySpanExt;

// Generated by build.rs into src/proto/. Committed so reviewers see the wire
// shape without running cargo first; see DESIGN_DECISIONS.md.
pub mod hello {
    include!("proto/hello.rs");
}
mod grpc_interceptor;
mod telemetry;

use hello::greeter_server::{Greeter, GreeterServer};
use hello::{HelloReply, HelloRequest};

struct GreeterSvc {
    hello_counter: Counter<u64>,
    hello_duration: Histogram<f64>,
}

#[tonic::async_trait]
impl Greeter for GreeterSvc {
    #[instrument(skip(self, req))]
    async fn say_hello(
        &self,
        req: Request<HelloRequest>,
    ) -> Result<Response<HelloReply>, Status> {
        // Stitch into the upstream trace: extract B3 (or W3C) headers from
        // incoming gRPC metadata, set them as the parent of the span the
        // #[instrument] macro just created. Must happen here, not in an
        // interceptor — interceptors run before Span::current() points at
        // the handler span.
        let parent_cx = grpc_interceptor::parent_context(req.metadata());
        let _ = Span::current().set_parent(parent_cx);

        let start = Instant::now();
        let name = req.into_inner().name;
        let name = if name.is_empty() { "world".to_string() } else { name };
        self.hello_counter.add(1, &[]);
        let reply = HelloReply {
            message: format!("hello, {name}"),
        };
        self.hello_duration
            .record(start.elapsed().as_secs_f64(), &[]);
        Ok(Response::new(reply))
    }
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let _guard = telemetry::init()?;

    let meter = global::meter("server");
    let hello_counter = meter
        .u64_counter("say_hello_total")
        .with_description("Total say_hello gRPC requests")
        .build();
    let hello_duration = meter
        .f64_histogram("say_hello_duration_seconds")
        .with_description("say_hello handler duration in seconds")
        .build();

    let addr: SocketAddr = std::env::var("SERVER_ADDR")
        .unwrap_or_else(|_| "0.0.0.0:50051".to_string())
        .parse()?;
    tracing::info!(%addr, "server: listening");

    Server::builder()
        .add_service(GreeterServer::new(GreeterSvc {
            hello_counter,
            hello_duration,
        }))
        .serve(addr)
        .await?;

    Ok(())
}
