#!/usr/bin/env python3
"""Read each service_catalog/<plugin>/plugin.toml's `[identity]` block,
emit per-plugin variables into `.env.localmesh` for compose interpolation.

Bridge between `plugin.toml`'s source-of-truth and the two-channel identity
tuple (docker labels + OTel SDK env). See
docs/superpowers/specs/2026-05-18-localmesh-service-mesh-design.md §6.

TODO: needs_prod_decisions replace generated .env entries with a build-step
compose overlay generator once compose grows a real extension mechanism.
"""
import os
import pathlib
import tomllib

CATALOG = pathlib.Path(os.environ.get("CATALOG_DIR", "service_catalog"))
OUT = pathlib.Path(os.environ.get("OUT_FILE", ".env.localmesh"))


def main():
    lines = [
        "# Auto-generated by scripts/localmesh-gen-plugin-env.py. Do not edit by hand.",
        "# Source of truth: service_catalog/*/plugin.toml [identity] blocks.",
        "",
    ]
    for manifest in sorted(CATALOG.rglob("plugin.toml")):
        plugin = tomllib.loads(manifest.read_text())
        ident = plugin.get("identity", {})
        if not ident:
            continue
        slug = manifest.parent.name
        prefix = slug.upper().replace("-", "_")
        if "module_name" in ident:
            lines.append(f"{prefix}_MODULE_NAME={ident['module_name']}")
        if "owned_by" in ident:
            lines.append(f"{prefix}_OWNED_BY={ident['owned_by']}")
        lines.append("")
    OUT.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
