apiVersion: v1
kind: Service
metadata:
  annotations:
    katenary.v3/compose-hash: 7254d38a3901f929396e016f1e161398870c9378
    katenary.v3/version: 3.0.0-rc6
  labels:
    {{- include "challenge.labels" . | nindent 4 }}
    katenary.v3/component: grafana
  name: '{{ include "challenge.fullname" . }}-grafana'
spec:
  ports:
  - name: port-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    {{- include "challenge.selectorLabels" . | nindent 4 }}
    katenary.v3/component: grafana
